import {
  User,
  DashboardSummary,
  SensorNode,
  SensorReading,
  RiskSummary,
  Alert,
  MeshNetwork,
  SystemHealth
} from '../types';

export const MOCK_USER: User = {
  id: 1,
  email: 'admin@coal.gov.in',
  full_name: 'Mine Safety Officer (SECL)',
  role: 'ADMIN'
};

export const MOCK_SENSORS_BASE: SensorNode[] = [
  {
    id: "N01",
    panel_id: "PANEL-B1",
    name: "LoRa Substation Gateway Hub",
    latitude: 22.3600,
    longitude: 82.7490,
    hardware_model: "LoRa-Gateway-Hub-SX1302",
    mesh_parent_id: null,
    is_gateway: true,
    status: "ONLINE",
    battery_level: 98.5,
    signal_strength_rssi: -58,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 101,
      node_id: "N01",
      timestamp: new Date().toISOString(),
      tilt_x: 0.05,
      tilt_y: 0.08,
      displacement: 0.4,
      vibration: 0.04,
      crack_detected: false,
      battery_level: 98.5,
      signal_strength: -58,
      anomaly_score: 5.2,
      is_outlier: false,
      resultant_tilt: 0.09
    }
  },
  {
    id: "N02",
    panel_id: "PANEL-A1",
    name: "Surface Sensor A1-West",
    latitude: 22.3550,
    longitude: 82.7450,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N01",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 91.2,
    signal_strength_rssi: -68,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 102,
      node_id: "N02",
      timestamp: new Date().toISOString(),
      tilt_x: 0.12,
      tilt_y: 0.14,
      displacement: 0.8,
      vibration: 0.06,
      crack_detected: false,
      battery_level: 91.2,
      signal_strength: -68,
      anomaly_score: 8.1,
      is_outlier: false,
      resultant_tilt: 0.18
    }
  },
  {
    id: "N03",
    panel_id: "PANEL-A1",
    name: "Surface Sensor A1-East",
    latitude: 22.3575,
    longitude: 82.7470,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N02",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 89.4,
    signal_strength_rssi: -71,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 103,
      node_id: "N03",
      timestamp: new Date().toISOString(),
      tilt_x: 0.10,
      tilt_y: 0.11,
      displacement: 0.9,
      vibration: 0.05,
      crack_detected: false,
      battery_level: 89.4,
      signal_strength: -71,
      anomaly_score: 7.4,
      is_outlier: false,
      resultant_tilt: 0.15
    }
  },
  {
    id: "N04",
    panel_id: "PANEL-A2",
    name: "Surface Sensor A2-South",
    latitude: 22.3555,
    longitude: 82.7525,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N01",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 88.0,
    signal_strength_rssi: -69,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 104,
      node_id: "N04",
      timestamp: new Date().toISOString(),
      tilt_x: 0.18,
      tilt_y: 0.22,
      displacement: 1.4,
      vibration: 0.07,
      crack_detected: false,
      battery_level: 88.0,
      signal_strength: -69,
      anomaly_score: 11.2,
      is_outlier: false,
      resultant_tilt: 0.28
    }
  },
  {
    id: "N05",
    panel_id: "PANEL-A2",
    name: "Surface Sensor A2-North",
    latitude: 22.3580,
    longitude: 82.7545,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N04",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 86.5,
    signal_strength_rssi: -74,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 105,
      node_id: "N05",
      timestamp: new Date().toISOString(),
      tilt_x: 0.15,
      tilt_y: 0.19,
      displacement: 1.1,
      vibration: 0.06,
      crack_detected: false,
      battery_level: 86.5,
      signal_strength: -74,
      anomaly_score: 9.8,
      is_outlier: false,
      resultant_tilt: 0.24
    }
  },
  {
    id: "N06",
    panel_id: "PANEL-B1",
    name: "Continuous Miner B1-P1",
    latitude: 22.3615,
    longitude: 82.7450,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N01",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 93.0,
    signal_strength_rssi: -64,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 106,
      node_id: "N06",
      timestamp: new Date().toISOString(),
      tilt_x: 0.22,
      tilt_y: 0.25,
      displacement: 1.8,
      vibration: 0.12,
      crack_detected: false,
      battery_level: 93.0,
      signal_strength: -64,
      anomaly_score: 14.5,
      is_outlier: false,
      resultant_tilt: 0.33
    }
  },
  {
    id: "N07",
    panel_id: "PANEL-B1",
    name: "Continuous Miner B1-P2",
    latitude: 22.3635,
    longitude: 82.7470,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N06",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 84.1,
    signal_strength_rssi: -72,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 107,
      node_id: "N07",
      timestamp: new Date().toISOString(),
      tilt_x: 0.19,
      tilt_y: 0.21,
      displacement: 1.6,
      vibration: 0.10,
      crack_detected: false,
      battery_level: 84.1,
      signal_strength: -72,
      anomaly_score: 13.0,
      is_outlier: false,
      resultant_tilt: 0.28
    }
  },
  {
    id: "N08",
    panel_id: "PANEL-B1",
    name: "Continuous Miner B1-P3",
    latitude: 22.3640,
    longitude: 82.7445,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N07",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 82.0,
    signal_strength_rssi: -76,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 108,
      node_id: "N08",
      timestamp: new Date().toISOString(),
      tilt_x: 0.14,
      tilt_y: 0.17,
      displacement: 1.3,
      vibration: 0.08,
      crack_detected: false,
      battery_level: 82.0,
      signal_strength: -76,
      anomaly_score: 10.5,
      is_outlier: false,
      resultant_tilt: 0.22
    }
  },
  {
    id: "N09",
    panel_id: "PANEL-B2",
    name: "Development Gallery B2-Entry",
    latitude: 22.3610,
    longitude: 82.7515,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N01",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 90.5,
    signal_strength_rssi: -66,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 109,
      node_id: "N09",
      timestamp: new Date().toISOString(),
      tilt_x: 0.16,
      tilt_y: 0.18,
      displacement: 1.5,
      vibration: 0.09,
      crack_detected: false,
      battery_level: 90.5,
      signal_strength: -66,
      anomaly_score: 11.9,
      is_outlier: false,
      resultant_tilt: 0.24
    }
  },
  {
    id: "N10",
    panel_id: "PANEL-B2",
    name: "Development Gallery B2-Mid",
    latitude: 22.3630,
    longitude: 82.7535,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N09",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 87.2,
    signal_strength_rssi: -70,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 110,
      node_id: "N10",
      timestamp: new Date().toISOString(),
      tilt_x: 0.21,
      tilt_y: 0.24,
      displacement: 1.9,
      vibration: 0.11,
      crack_detected: false,
      battery_level: 87.2,
      signal_strength: -70,
      anomaly_score: 14.1,
      is_outlier: false,
      resultant_tilt: 0.32
    }
  },
  {
    id: "N11",
    panel_id: "PANEL-B2",
    name: "Development Gallery B2-Deep",
    latitude: 22.3645,
    longitude: 82.7520,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N10",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 85.0,
    signal_strength_rssi: -73,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 111,
      node_id: "N11",
      timestamp: new Date().toISOString(),
      tilt_x: 0.25,
      tilt_y: 0.28,
      displacement: 2.1,
      vibration: 0.13,
      crack_detected: false,
      battery_level: 85.0,
      signal_strength: -73,
      anomaly_score: 15.8,
      is_outlier: false,
      resultant_tilt: 0.38
    }
  },
  {
    id: "N12",
    panel_id: "PANEL-B3",
    name: "Panel B3 South Extent",
    latitude: 22.3625,
    longitude: 82.7555,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N10",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 88.0,
    signal_strength_rssi: -72,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 112,
      node_id: "N12",
      timestamp: new Date().toISOString(),
      tilt_x: 0.35,
      tilt_y: 0.42,
      displacement: 2.8,
      vibration: 0.16,
      crack_detected: false,
      battery_level: 88.0,
      signal_strength: -72,
      anomaly_score: 18.2,
      is_outlier: false,
      resultant_tilt: 0.55
    }
  },
  {
    id: "N13",
    panel_id: "PANEL-B3",
    name: "Panel B3 Trough Flank",
    latitude: 22.3635,
    longitude: 82.7570,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N12",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 84.5,
    signal_strength_rssi: -75,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 113,
      node_id: "N13",
      timestamp: new Date().toISOString(),
      tilt_x: 0.48,
      tilt_y: 0.55,
      displacement: 3.6,
      vibration: 0.19,
      crack_detected: false,
      battery_level: 84.5,
      signal_strength: -75,
      anomaly_score: 21.0,
      is_outlier: false,
      resultant_tilt: 0.73
    }
  },
  {
    id: "N14",
    panel_id: "PANEL-B3",
    name: "Panel B3 Core Depillaring Epicenter",
    latitude: 22.3645,
    longitude: 82.7570,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N13",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 81.3,
    signal_strength_rssi: -77,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 114,
      node_id: "N14",
      timestamp: new Date().toISOString(),
      tilt_x: 0.52,
      tilt_y: 0.61,
      displacement: 4.2,
      vibration: 0.22,
      crack_detected: false,
      battery_level: 81.3,
      signal_strength: -77,
      anomaly_score: 24.5,
      is_outlier: false,
      resultant_tilt: 0.80
    }
  },
  {
    id: "N15",
    panel_id: "PANEL-B3",
    name: "Panel B3 Crown Extent",
    latitude: 22.3655,
    longitude: 82.7575,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N14",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 79.8,
    signal_strength_rssi: -79,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 115,
      node_id: "N15",
      timestamp: new Date().toISOString(),
      tilt_x: 0.45,
      tilt_y: 0.50,
      displacement: 3.4,
      vibration: 0.18,
      crack_detected: false,
      battery_level: 79.8,
      signal_strength: -79,
      anomaly_score: 19.8,
      is_outlier: false,
      resultant_tilt: 0.67
    }
  },
  {
    id: "N16",
    panel_id: "PANEL-B3",
    name: "Panel B3 North Boundary",
    latitude: 22.3665,
    longitude: 82.7580,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N15",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 83.2,
    signal_strength_rssi: -81,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 116,
      node_id: "N16",
      timestamp: new Date().toISOString(),
      tilt_x: 0.32,
      tilt_y: 0.38,
      displacement: 2.5,
      vibration: 0.15,
      crack_detected: false,
      battery_level: 83.2,
      signal_strength: -81,
      anomaly_score: 16.2,
      is_outlier: false,
      resultant_tilt: 0.50
    }
  },
  {
    id: "N17",
    panel_id: "PANEL-B3",
    name: "Panel B3 East Wing 1",
    latitude: 22.3620,
    longitude: 82.7585,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N12",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 87.0,
    signal_strength_rssi: -76,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 117,
      node_id: "N17",
      timestamp: new Date().toISOString(),
      tilt_x: 0.28,
      tilt_y: 0.31,
      displacement: 2.0,
      vibration: 0.12,
      crack_detected: false,
      battery_level: 87.0,
      signal_strength: -76,
      anomaly_score: 14.8,
      is_outlier: false,
      resultant_tilt: 0.42
    }
  },
  {
    id: "N18",
    panel_id: "PANEL-B3",
    name: "Panel B3 East Wing 2",
    latitude: 22.3640,
    longitude: 82.7590,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N17",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 85.5,
    signal_strength_rssi: -78,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 118,
      node_id: "N18",
      timestamp: new Date().toISOString(),
      tilt_x: 0.30,
      tilt_y: 0.34,
      displacement: 2.2,
      vibration: 0.13,
      crack_detected: false,
      battery_level: 85.5,
      signal_strength: -78,
      anomaly_score: 15.5,
      is_outlier: false,
      resultant_tilt: 0.45
    }
  },
  {
    id: "N19",
    panel_id: "PANEL-B3",
    name: "Panel B3 East Wing 3",
    latitude: 22.3660,
    longitude: 82.7595,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N18",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 82.8,
    signal_strength_rssi: -82,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 119,
      node_id: "N19",
      timestamp: new Date().toISOString(),
      tilt_x: 0.26,
      tilt_y: 0.29,
      displacement: 1.9,
      vibration: 0.11,
      crack_detected: false,
      battery_level: 82.8,
      signal_strength: -82,
      anomaly_score: 13.9,
      is_outlier: false,
      resultant_tilt: 0.39
    }
  },
  {
    id: "N20",
    panel_id: "PANEL-B3",
    name: "Panel B3 West Wing 1",
    latitude: 22.3620,
    longitude: 82.7535,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N10",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 89.0,
    signal_strength_rssi: -71,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 120,
      node_id: "N20",
      timestamp: new Date().toISOString(),
      tilt_x: 0.22,
      tilt_y: 0.26,
      displacement: 1.7,
      vibration: 0.10,
      crack_detected: false,
      battery_level: 89.0,
      signal_strength: -71,
      anomaly_score: 12.8,
      is_outlier: false,
      resultant_tilt: 0.34
    }
  },
  {
    id: "N21",
    panel_id: "PANEL-B3",
    name: "Panel B3 West Wing 2",
    latitude: 22.3640,
    longitude: 82.7540,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N20",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 86.0,
    signal_strength_rssi: -74,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 121,
      node_id: "N21",
      timestamp: new Date().toISOString(),
      tilt_x: 0.29,
      tilt_y: 0.33,
      displacement: 2.1,
      vibration: 0.12,
      crack_detected: false,
      battery_level: 86.0,
      signal_strength: -74,
      anomaly_score: 15.0,
      is_outlier: false,
      resultant_tilt: 0.44
    }
  },
  {
    id: "N22",
    panel_id: "PANEL-B3",
    name: "Panel B3 West Wing 3",
    latitude: 22.3660,
    longitude: 82.7545,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N21",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 83.5,
    signal_strength_rssi: -78,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 122,
      node_id: "N22",
      timestamp: new Date().toISOString(),
      tilt_x: 0.24,
      tilt_y: 0.28,
      displacement: 1.8,
      vibration: 0.11,
      crack_detected: false,
      battery_level: 83.5,
      signal_strength: -78,
      anomaly_score: 13.5,
      is_outlier: false,
      resultant_tilt: 0.37
    }
  },
  {
    id: "N23",
    panel_id: "PANEL-B3",
    name: "Panel B3 South-East Outpost",
    latitude: 22.3615,
    longitude: 82.7575,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N17",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 88.5,
    signal_strength_rssi: -75,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 123,
      node_id: "N23",
      timestamp: new Date().toISOString(),
      tilt_x: 0.20,
      tilt_y: 0.23,
      displacement: 1.5,
      vibration: 0.09,
      crack_detected: false,
      battery_level: 88.5,
      signal_strength: -75,
      anomaly_score: 11.5,
      is_outlier: false,
      resultant_tilt: 0.30
    }
  },
  {
    id: "N24",
    panel_id: "PANEL-B3",
    name: "Panel B3 North-East Perimeter",
    latitude: 22.3670,
    longitude: 82.7585,
    hardware_model: "ESP32-SX1262-TiltNode",
    mesh_parent_id: "N19",
    is_gateway: false,
    status: "ONLINE",
    battery_level: 81.0,
    signal_strength_rssi: -83,
    last_seen_at: new Date().toISOString(),
    latest_reading: {
      id: 124,
      node_id: "N24",
      timestamp: new Date().toISOString(),
      tilt_x: 0.21,
      tilt_y: 0.25,
      displacement: 1.6,
      vibration: 0.10,
      crack_detected: false,
      battery_level: 81.0,
      signal_strength: -83,
      anomaly_score: 12.0,
      is_outlier: false,
      resultant_tilt: 0.33
    }
  }
];

export const MOCK_SUMMARY: DashboardSummary = {
  mine_name: "Korba Underground Coal Mine (Block-A)",
  active_panel: "PANEL-B3",
  system_status: "HEALTHY",
  active_sensor_nodes: 24,
  offline_sensor_nodes: 0,
  current_risk_level: "NORMAL",
  current_risk_score: 14.5,
  active_alerts_count: 0,
  area_under_monitoring_sq_km: 4.85,
  last_data_update: new Date().toISOString(),
  disclaimer: "Real-time decision support system for Smart India Hackathon."
};

export const MOCK_RISK_SUMMARY: RiskSummary = {
  current_risk_score: 14.5,
  risk_classification: "NORMAL",
  primary_panel: "PANEL-B3",
  affected_cluster: "Panel B3 Baseline",
  factors: {
    "Displacement Velocity": 12.0,
    "Tilt Angle Increase": 10.0,
    "Spatial Correlation": 8.0,
    "Vibration RMS": 11.0
  },
  trend_direction: "STABLE",
  scientific_disclaimer: "Prototype / Simulated Sensor Data. Decision support platform.",
  explanation: "All panels within permissible geotechnical tolerance limits. Normal operations."
};

export const MOCK_ALERTS: Alert[] = [
  {
    id: "ALT-1000",
    panel_id: "PANEL-B3",
    node_cluster: "Cluster N14-N15",
    title: "Critical Subsidence Warning: Accelerated Surface Micro-Strain",
    condition_detected: "Elevated micro-strain and resultant tilt (2.45°) detected in Panel B3 depillaring boundary. Continuous displacement recorded at 14.8mm.",
    severity: "CRITICAL",
    status: "ACTIVE",
    ai_risk_score: 84.5,
    measured_tilt: 2.45,
    measured_displacement: 14.8,
    crack_detected: true,
    recommended_action: "Halt depillaring operations in Panel B3. Trigger surface perimeter siren and dispatch emergency bulletins to safety officers.",
    created_at: new Date(Date.now() - 300000).toISOString()
  },
  {
    id: "ALT-1001",
    panel_id: "PANEL-B3",
    node_cluster: "Cluster N12-N15",
    title: "Subsidence Risk Advisory Notice",
    condition_detected: "Elevated micro-strain detected in Panel B3 depillaring boundary.",
    severity: "WARNING",
    status: "ACKNOWLEDGED",
    ai_risk_score: 42.0,
    measured_tilt: 1.85,
    measured_displacement: 8.2,
    crack_detected: false,
    recommended_action: "Conduct secondary optical leveling check on Panel B3 surface monuments.",
    acknowledged_by: "R Sai Sankeerth Reddy",
    acknowledged_at: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 7200000).toISOString()
  },
  {
    id: "ALT-1002",
    panel_id: "PANEL-A2",
    node_cluster: "Node N04-N05",
    title: "Post-Depillaring Settlement Baseline Reached",
    condition_detected: "Settlement rate stabilized below 0.05 mm/hr over 48h observation period.",
    severity: "WARNING",
    status: "RESOLVED",
    ai_risk_score: 22.0,
    measured_tilt: 0.45,
    measured_displacement: 3.1,
    crack_detected: false,
    recommended_action: "Transition Panel A2 to low-frequency quiescent telemetry schedule.",
    acknowledged_by: "Chief Geologist",
    acknowledged_at: new Date(Date.now() - 86400000).toISOString(),
    resolved_at: new Date(Date.now() - 43200000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString()
  }
];

export function generateMockReadings(sensorId: string = 'N14', hours: number = 24): SensorReading[] {
  const points = Math.min(hours * 2, 48);
  const now = Date.now();
  const stepMs = (hours * 3600 * 1000) / points;
  const readings: SensorReading[] = [];

  for (let i = points; i >= 0; i--) {
    const t = new Date(now - i * stepMs).toISOString();
    const progress = (points - i) / points;
    const baseTilt = 0.3 + progress * 0.4 + Math.sin(i * 0.5) * 0.08;
    const baseDisp = 1.0 + progress * 2.5 + Math.cos(i * 0.3) * 0.2;
    const baseVib = 0.08 + Math.random() * 0.06;
    const anomaly = Math.min(95, Math.max(5, 12 + progress * 15 + Math.random() * 5));

    readings.push({
      id: 1000 + i,
      node_id: sensorId,
      timestamp: t,
      tilt_x: Number((baseTilt * 0.6).toFixed(3)),
      tilt_y: Number((baseTilt * 0.8).toFixed(3)),
      displacement: Number(baseDisp.toFixed(2)),
      vibration: Number(baseVib.toFixed(3)),
      crack_detected: false,
      battery_level: Number((95 - progress * 8).toFixed(1)),
      signal_strength: -70 - Math.floor(Math.random() * 6),
      anomaly_score: Number(anomaly.toFixed(1)),
      is_outlier: false,
      resultant_tilt: Number(baseTilt.toFixed(3))
    });
  }
  return readings;
}

export function generateMockMesh(): MeshNetwork {
  const links = [
    { id: 1, source_node_id: "N02", target_node_id: "N01", link_quality_lqi: 92, rssi: -68, hop_count: 1, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 2, source_node_id: "N03", target_node_id: "N02", link_quality_lqi: 88, rssi: -71, hop_count: 2, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 3, source_node_id: "N04", target_node_id: "N01", link_quality_lqi: 90, rssi: -69, hop_count: 1, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 4, source_node_id: "N05", target_node_id: "N04", link_quality_lqi: 85, rssi: -74, hop_count: 2, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 5, source_node_id: "N06", target_node_id: "N01", link_quality_lqi: 95, rssi: -64, hop_count: 1, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 6, source_node_id: "N07", target_node_id: "N06", link_quality_lqi: 86, rssi: -72, hop_count: 2, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 7, source_node_id: "N08", target_node_id: "N07", link_quality_lqi: 82, rssi: -76, hop_count: 3, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 8, source_node_id: "N09", target_node_id: "N01", link_quality_lqi: 94, rssi: -66, hop_count: 1, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 9, source_node_id: "N10", target_node_id: "N09", link_quality_lqi: 89, rssi: -70, hop_count: 2, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 10, source_node_id: "N11", target_node_id: "N10", link_quality_lqi: 86, rssi: -73, hop_count: 3, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 11, source_node_id: "N12", target_node_id: "N10", link_quality_lqi: 87, rssi: -72, hop_count: 3, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 12, source_node_id: "N13", target_node_id: "N12", link_quality_lqi: 84, rssi: -75, hop_count: 4, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 13, source_node_id: "N14", target_node_id: "N13", link_quality_lqi: 81, rssi: -77, hop_count: 5, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 14, source_node_id: "N15", target_node_id: "N14", link_quality_lqi: 80, rssi: -79, hop_count: 6, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 15, source_node_id: "N16", target_node_id: "N15", link_quality_lqi: 77, rssi: -81, hop_count: 7, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 16, source_node_id: "N17", target_node_id: "N12", link_quality_lqi: 83, rssi: -76, hop_count: 4, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 17, source_node_id: "N18", target_node_id: "N17", link_quality_lqi: 80, rssi: -78, hop_count: 5, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 18, source_node_id: "N19", target_node_id: "N18", link_quality_lqi: 76, rssi: -82, hop_count: 6, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 19, source_node_id: "N20", target_node_id: "N10", link_quality_lqi: 88, rssi: -71, hop_count: 3, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 20, source_node_id: "N21", target_node_id: "N20", link_quality_lqi: 84, rssi: -74, hop_count: 4, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 21, source_node_id: "N22", target_node_id: "N21", link_quality_lqi: 81, rssi: -78, hop_count: 5, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 22, source_node_id: "N23", target_node_id: "N17", link_quality_lqi: 84, rssi: -75, hop_count: 5, status: "ACTIVE" as const, updated_at: new Date().toISOString() },
    { id: 23, source_node_id: "N24", target_node_id: "N19", link_quality_lqi: 75, rssi: -83, hop_count: 7, status: "ACTIVE" as const, updated_at: new Date().toISOString() }
  ];

  return {
    gateway_id: "N01",
    total_nodes: 24,
    online_nodes: 24,
    average_rssi: -73.2,
    max_hops: 7,
    network_health: "HEALTHY",
    nodes: MOCK_SENSORS_BASE,
    links
  };
}

export const MOCK_SYSTEM_HEALTH: SystemHealth = {
  gateway_status: "ONLINE",
  database_status: "ONLINE",
  ai_engine_status: "RUNNING",
  mesh_network_status: "HEALTHY",
  mqtt_status: "ONLINE",
  total_nodes: 24,
  nodes_online: 24,
  nodes_offline: 0,
  nodes_low_battery: 0,
  nodes_weak_signal: 0,
  last_synchronization: new Date().toISOString(),
  uptime_seconds: 184520,
  cpu_usage_pct: 18.4,
  memory_usage_mb: 138.2
};
